Bootstrap: docker
From: eicweb.phy.anl.gov:4567/monte_carlo/liege/liege:latest

%help
  liege quarkonium generator container
  Tools: 
     - liege      : main generator
     - root       : root version as used by liege

%labels
  Maintainer "Sylvester Joosten"
  Version v3.0

%environment -c /bin/bash
  export PYTHONPATH=/usr/local/lib:$PYTHONPATH
  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  source /usr/local/bin/thisroot.sh

%post -c /bin/bash
  echo "  -------------------------------------------------"
  echo "  ===> Image setup complete"
  echo "  -------------------------------------------------"

# ===================================
# GLOBAL
# ===================================

%environment -c /bin/bash
  export PYTHONPATH=/usr/local/lib:$PYTHONPATH
  export PATH=/usr/loca/bin:${PATH}
  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  export ROOT_INCLUDE_PATH=/usr/local/include

%runscript
  echo "Launching a shell in the liege container."
  echo "Use through singularity apps recommended (see help for more info)."
  exec bash

# =======================
# liege
# =======================
%apprun liege
  liege "$@"

%appenv liege
  export PYTHONPATH=/usr/local/lib:${PYTHONPATH}
  export PATH=/usr/local/bin:${PATH}
  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  export ROOT_INCLUDE_PATH=/usr/local/include/podd:/usr/local/include/hcana

# =======================
# root
# =======================
%apprun root
  root "$@"

%appenv root
  export PYTHONPATH=/usr/local/lib:${PYTHONPATH}
  export PATH=/usr/local/bin:${PATH}
  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  export ROOT_INCLUDE_PATH=/usr/local/include/podd:/usr/local/include/hcana
